### ISSUE TITLE
Connecting to SP5500  via serial?

### ISSUE THREAD

**Issue by gytisgreitai** [jpbarraca/pai#25]
Serial used:

```
 3115.085884] usb 3-1: new full-speed USB device number 7 using ohci-platform
[ 3115.356874] usb 3-1: New USB device found, idVendor=067b, idProduct=2303
[ 3115.356886] usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 3115.356892] usb 3-1: Product: USB-Serial Controller
[ 3115.356898] usb 3-1: Manufacturer: Prolific Technology Inc.
[ 3115.359234] pl2303 3-1:1.0: pl2303 converter detected
[ 3115.381351] usb 3-1: pl2303 converter now attached to ttyUSB0
```

When connecting I get this error:

```
2018-12-11 20:10:46,901 - INFO     - PAI - Starting Paradox Alarm Interface
2018-12-11 20:10:46,903 - INFO     - PAI - Console Log level set to 10
2018-12-11 20:10:47,906 - INFO     - PAI - Using Serial Connection
2018-12-11 20:10:47,936 - INFO     - PAI - Starting...
2018-12-11 20:10:47,938 - INFO     - PAI.paradox.paradox - Connecting to interface
2018-12-11 20:10:47,939 - DEBUG    - PAI.paradox.connections.serial_connection - Opening Serial port: /dev/ttyUSB0
2018-12-11 20:10:47,957 - DEBUG    - PAI.paradox.connections.serial_connection - Serial port open!
2018-12-11 20:10:47,958 - INFO     - PAI.paradox.paradox - Connecting to panel
2018-12-11 20:10:47,960 - INFO     - PAI.paradox.paradox - Initiating communication
2018-12-11 20:10:47,968 - DEBUG    - PAI.paradox.paradox - PC -> A b'72000000000000000000000000000000000000000000000000000000000000000000000072'
2018-12-11 20:10:48,011 - DEBUG    - PAI.paradox.paradox - PC <- A b'72000000000000000000000000000000000000000000000000000000000000000000000072'
2018-12-11 20:10:48,014 - DEBUG    - PAI.paradox.paradox - Container:
    fields = Container:
        length = 36
        value = Container:
            po = Container:
                command = 7
                reserved0 = 2
            reserved1 = None
        data = b'r\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'... (truncated, total 36)
        offset2 = 36
        offset1 = 0
    checksum = b'r' (total 1)
2018-12-11 20:10:48,019 - ERROR    - PAI.paradox.paradox - Connect error
Traceback (most recent call last):
  File "/home/gytis/.local/lib/python3.5/site-packages/construct/lib/containers.py", line 100, in __getattr__
    return self[name]
KeyError: 'label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gytis/pai/paradox/paradox.py", line 78, in connect
    (reply.fields.value.label.strip(b'\0 ').decode('utf-8')),
  File "/home/gytis/.local/lib/python3.5/site-packages/construct/lib/containers.py", line 102, in __getattr__
    raise AttributeError(name)
AttributeError: label
2018-12-11 20:10:48,026 - ERROR    - PAI - Unable to connect to alarm
```

Tried to change the 78th line to:

```
                logger.info("DEBUG FOUND PANEL {}".format(reply.fields.value))
                #logger.info("Found Panel {} version {}.{} build {}".format(
                #    (reply.fields.value.label.strip(b'\0 ').decode('utf-8')),
                #    reply.fields.value.application.version,
                #     reply.fields.value.application.revision,
                #     reply.fields.value.application.build))
```

But then it fails with this:

```
2018-12-11 20:20:22,122 - INFO     - PAI - Starting Paradox Alarm Interface
2018-12-11 20:20:22,123 - INFO     - PAI - Console Log level set to 10
2018-12-11 20:20:23,126 - INFO     - PAI - Using Serial Connection
2018-12-11 20:20:23,156 - INFO     - PAI - Starting...
2018-12-11 20:20:23,157 - INFO     - PAI.paradox.paradox - Connecting to interface
2018-12-11 20:20:23,158 - DEBUG    - PAI.paradox.connections.serial_connection - Opening Serial port: /dev/ttyUSB0
2018-12-11 20:20:23,176 - DEBUG    - PAI.paradox.connections.serial_connection - Serial port open!
2018-12-11 20:20:23,177 - INFO     - PAI.paradox.paradox - Connecting to panel
2018-12-11 20:20:23,179 - INFO     - PAI.paradox.paradox - Initiating communication
2018-12-11 20:20:23,187 - DEBUG    - PAI.paradox.paradox - PC -> A b'72000000000000000000000000000000000000000000000000000000000000000000000072'
2018-12-11 20:20:23,229 - DEBUG    - PAI.paradox.paradox - PC <- A b'72000000000000000000000000000000000000000000000000000000000000000000000072'
2018-12-11 20:20:23,232 - DEBUG    - PAI.paradox.paradox - Container:
    fields = Container:
        data = b'r\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'... (truncated, total 36)
        offset1 = 0
        offset2 = 36
        length = 36
        value = Container:
            po = Container:
                command = 7
                reserved0 = 2
            reserved1 = None
    checksum = b'r' (total 1)
2018-12-11 20:20:23,237 - INFO     - PAI.paradox.paradox - DEBUG FOUND PANEL Container:
    po = Container:
        command = 7
        reserved0 = 2
    reserved1 = None
2018-12-11 20:20:23,238 - INFO     - PAI.paradox.paradox - Starting communication
2018-12-11 20:20:23,245 - DEBUG    - PAI.paradox.paradox - PC -> A b'5f200000000000000000000000000000000000000000000000000000000000000002000081'
2018-12-11 20:20:23,287 - DEBUG    - PAI.paradox.paradox - PC <- A b'5f200000000000000000000000000000000000000000000000000000000000000002000081'
2018-12-11 20:20:23,291 - DEBUG    - PAI.paradox.paradox - Container:
    fields = Container:
        data = b'_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'... (truncated, total 36)
        offset1 = 0
        offset2 = 36
        length = 36
        value = Container:
            po = Container:
                command = 95
            validation = 32
            not_used0 = None
            source_id = (enum) Winload_IP 2
            user_id = Container:
                high = 0
                low = 0
    checksum = b'\x81' (total 1)
ERROR:root:Got message 95 but expected 0
ERROR:root:Detail:
Container:
    fields = Container:
        data = b'_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'... (truncated, total 36)
        offset1 = 0
        offset2 = 36
        length = 36
        value = Container:
            po = Container:
                command = 95
            validation = 32
            not_used0 = None
            source_id = (enum) Winload_IP 2
            user_id = Container:
                high = 0
                low = 0
    checksum = b'\x81' (total 1)
2018-12-11 20:20:23,298 - DEBUG    - PAI.paradox.paradox - PC -> A b'5f200000000000000000000000000000000000000000000000000000000000000002000081'
DEBUG:PAI.paradox.paradox:PC -> A b'5f200000000000000000000000000000000000000000000000000000000000000002000081'
2018-12-11 20:20:23,341 - DEBUG    - PAI.paradox.paradox - PC <- A b'5f200000000000000000000000000000000000000000000000000000000000000002000081'
DEBUG:PAI.paradox.paradox:PC <- A b'5f200000000000000000000000000000000000000000000000000000000000000002000081'
2018-12-11 20:20:23,345 - DEBUG    - PAI.paradox.paradox - Container:
    fields = Container:
        data = b'_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'... (truncated, total 36)
        offset1 = 0
        offset2 = 36
        length = 36
        value = Container:
            po = Container:
                command = 95
            validation = 32
            not_used0 = None
            source_id = (enum) Winload_IP 2
            user_id = Container:
                high = 0
                low = 0
    checksum = b'\x81' (total 1)
DEBUG:PAI.paradox.paradox:Container:
    fields = Container:
        data = b'_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'... (truncated, total 36)
        offset1 = 0
        offset2 = 36
        length = 36
        value = Container:
            po = Container:
                command = 95
            validation = 32
            not_used0 = None
            source_id = (enum) Winload_IP 2
            user_id = Container:
                high = 0
                low = 0
    checksum = b'\x81' (total 1)
ERROR:root:Got message 95 but expected 0
```

Any ideas? Previously i had code written on arduino and readonly events were consumed successfully

**Comment by jpbarraca** [comment]
One idea comes to my mind: there is a short between the TX and RX lines. You are receiving the messages sent without modification.

**Comment by gytisgreitai** [comment]
hm ok, maybe something messed with wiring. The adapter should be good, because if I hook it to arduino i can read messages via simple cat. And the arduino can read messages from paradox. But i'll try to do a complete rewire to dismiss this. Thanks.

**Comment by gytisgreitai** [comment]
Yep, something was wrong with the wiring. After that had to set password to None and it works. Thank you very much  !
```

2018-12-12 20:14:16,266 - INFO     - PAI - Starting Paradox Alarm Interface
2018-12-12 20:14:16,267 - INFO     - PAI - Console Log level set to 20
2018-12-12 20:14:17,270 - INFO     - PAI - Using Serial Connection
2018-12-12 20:14:17,299 - INFO     - PAI - Starting...
2018-12-12 20:14:17,301 - INFO     - PAI.paradox.paradox - Connecting to interface
2018-12-12 20:14:17,318 - INFO     - PAI.paradox.paradox - Connecting to panel
2018-12-12 20:14:17,320 - INFO     - PAI.paradox.paradox - Initiating communication
2018-12-12 20:14:17,419 - INFO     - PAI.paradox.paradox - Found Panel SP5500 version 4.148 build 0
2018-12-12 20:14:17,421 - INFO     - PAI.paradox.paradox - Starting communication.


```

**Comment by jpbarraca** [comment]
Great!. Logfiles were deleted.
