### ISSUE TITLE
AssertionError in EVO192 loop: assert vars.address in RAMDataParserMap

### ISSUE THREAD

**Issue by aivarlo** [jpbarraca/pai#26]
When tried latest master code (first time) with my EVO192 got AssertionError after entering loop:

> 2018-12-13 16:32:21,925 - INFO     - PAI.paradox.paradox - Connection OK
> 2018-12-13 16:32:21,926 - DEBUG    - PAI.paradox.paradox - Loop start
> 2018-12-13 16:32:21,959 - ERROR    - PAI.paradox.paradox - Loop
> Traceback (most recent call last):
>   File "/home/aivar/git/pai/paradox/paradox.py", line 146, in loop
>     self.panel.handle_status(reply)
>   File "/home/aivar/git/pai/paradox/hardware/evo/panel.py", line 147, in handle_status
>     assert vars.address in RAMDataParserMap
> AssertionError
> 2018-12-13 16:32:32,032 - ERROR    - PAI.paradox.paradox - Loop
> Traceback (most recent call last):
>   File "/home/aivar/git/pai/paradox/paradox.py", line 146, in loop
>     self.panel.handle_status(reply)
>   File "/home/aivar/git/pai/paradox/hardware/evo/panel.py", line 147, in handle_status
>     assert vars.address in RAMDataParserMap
> AssertionError

IP connection seems to establish well:

> 2018-12-13 16:32:07,155 - DEBUG    - PAI.paradox.connections.ip_connection - Connecting to IP Panel
> 2018-12-13 16:32:07,155 - DEBUG    - PAI.paradox.connections.ip_connection - IP Connection established
> 2018-12-13 16:32:07,160 - INFO     - PAI.paradox.connections.ip_connection - Connected to IP Module. Version 20, Firmware:                                                                          1.38, Serial: 7101c1c9

and:

> 2018-12-13 16:32:07,171 - INFO     - PAI.paradox.connections.ip_connection - Connection fully established
> 2018-12-13 16:32:07,171 - INFO     - PAI.paradox.paradox - Connecting to panel
> 2018-12-13 16:32:07,171 - INFO     - PAI.paradox.paradox - Initiating communication
> 2018-12-13 16:32:07,197 - INFO     - PAI.paradox.paradox - Found Panel EVO192 version 2.144 build 25
> 2018-12-13 16:32:07,197 - INFO     - PAI.paradox.paradox - Starting communication
> 2018-12-13 16:32:07,233 - INFO     - PAI.paradox.hardware.evo.panel - Initializing communication
> 2018-12-13 16:32:07,255 - INFO     - PAI.paradox.hardware.evo.panel - Authentication Success

Zones, Partitions, Users seem to  read also correctly.

Edit:
in user.py I have set
```
SYNC_TIME = False
MQTT_ENABLE = True

```

**Comment by aivarlo** [comment]
Super, thank you! Error disappeared and events started to flow. Will close the issue.
