### ISSUE TITLE
EVO192: construct.core.ChecksumError: wrong checksum, read b'00', computed b'95'

### ISSUE THREAD

**Issue by aivarlo** [jpbarraca/pai#28]
got another issue, after running few hours ChecksumError appeared. There seems to be quiet period before it and then suddenly ChecksumError, then again  27 minutes quiet and again. Could it be related to some timeouts, reconnections or similar?

```
2018-12-14 13:56:19,723 - DEBUG    - PAI.paradox.paradox - Change partition/Maja/ready from False to True
2018-12-14 13:56:19,723 - DEBUG    - PAI.paradox.paradox - Change partition/Maja/all_zone_closed from False to True
2018-12-14 13:56:19,724 - DEBUG    - PAI.paradox.paradox - Change partition/Maja/stay_instant_ready from False to True
2018-12-14 14:23:30,421 - ERROR    - PAI.paradox.hardware.evo.panel - Parsing message: 47  80  00  00  05  00  00  00  00  00  00  00  00  00  00  00  00  00
 00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  0
0  00  00  00  00  00  00  00  00  00  00  00  1e  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
 00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
Traceback (most recent call last):
  File "/home/aivar/git/pai/paradox/hardware/evo/panel.py", line 85, in parse_message
    return PerformActionResponse.parse(message)
  File "/home/aivar/.local/lib/python3.6/site-packages/construct/core.py", line 304, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/home/aivar/.local/lib/python3.6/site-packages/construct/core.py", line 316, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/home/aivar/.local/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/aivar/.local/lib/python3.6/site-packages/construct/core.py", line 1979, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/home/aivar/.local/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/aivar/.local/lib/python3.6/site-packages/construct/core.py", line 2468, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/home/aivar/.local/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/aivar/.local/lib/python3.6/site-packages/construct/core.py", line 5161, in _parse
    hash2 if not isinstance(hash2,bytestringtype) else binascii.hexlify(hash2), ))
construct.core.ChecksumError: wrong checksum, read b'00', computed b'cc'
2018-12-14 14:23:30,422 - DEBUG    - PAI.paradox.paradox - Unknown message: 47  80  00  00  05  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00  00  00  00  00  00  00  00  00  1e  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
2018-12-14 14:51:41,881 - ERROR    - PAI.paradox.hardware.evo.panel - Parsing message: 47  80  00  00  04  00  00  00  00  00  01  00  00  00  00  00  01  00
 00  00  00  00  dd  07  fa  06  dd  07  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  0
0  00  00  00  00  00  00  00  00  00  00  00  e7  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
 00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
Traceback (most recent call last):
  File "/home/aivar/git/pai/paradox/hardware/evo/panel.py", line 85, in parse_message
    return PerformActionResponse.parse(message)
  File "/home/aivar/.local/lib/python3.6/site-packages/construct/core.py", line 304, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/home/aivar/.local/lib/python3.6/site-packages/construct/core.py", line 316, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/home/aivar/.local/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/aivar/.local/lib/python3.6/site-packages/construct/core.py", line 1979, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/home/aivar/.local/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/aivar/.local/lib/python3.6/site-packages/construct/core.py", line 2468, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/home/aivar/.local/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/aivar/.local/lib/python3.6/site-packages/construct/core.py", line 5161, in _parse
    hash2 if not isinstance(hash2,bytestringtype) else binascii.hexlify(hash2), ))
construct.core.ChecksumError: wrong checksum, read b'00', computed b'95'
2018-12-14 14:51:41,882 - DEBUG    - PAI.paradox.paradox - Unknown message: 47  80  00  00  04  00  00  00  00  00  01  00  00  00  00  00  01  00  00  00  00  00  dd  07  fa  06  dd  07  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  e7  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00

```

in user.py there are set limits, if that matters:
```
LIMITS = { # By default all zones will be monitored
    'zone': range(1, 100),     # Zones to monitor and control
    'user': [1, 2, 3],     # Users to consider
    # 'door': range(1, 32),     # Doors to consider
    # 'output': range(1, 17),   # Outputs to monitor and control
    'partition': [1, 2, 3],      # Partitions to monitor and control
    'bus-module': range(1, 17),      # Buses to monitor
    # 'repeater': range(1, 9),  # Repeaters to monitor
    # 'keypad': range(1, 9)     # Keypads to monitor
}

```

**Comment by yozik04** [comment]
Tere,
I also receive this periodically. No idea what it is. But packet is wrong. Feel free to debug =)

**Comment by jpbarraca** [comment]
This also happens here. No idea what is happening. The packets do not make sense.

**Comment by yozik04** [comment]
We can close that as we do not know how we can improve the situation.
