### ISSUE TITLE
GSM modem issues?

### ISSUE THREAD

**Issue by gytisgreitai** [jpbarraca/pai#30]
Trying to hook up sim800l via serial interface. I can send commands via screen successfully and it seems that gsm interfaces also connects ok, but when receiving message it crashes:

```
2018-12-15 14:07:32,024 - ERROR    - PAI.paradox.interfaces.gsm_interface - modem failed
Traceback (most recent call last):
  File "/home/gytis/.local/lib/python3.5/site-packages/serial/serialposix.py", line 501, in read
    'device reports readiness to read but returned no data '
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gytis/pai/paradox/interfaces/gsm_interface.py", line 111, in run
    data = self.port.read(200)
  File "/home/gytis/.local/lib/python3.5/site-packages/serial/serialposix.py", line 509, in read
    raise SerialException('read failed: {}'.format(e))
serial.serialutil.SerialException: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
2018-12-15 14:07:33,032 - INFO     - PAI.paradox.interfaces.gsm_interface - Using /dev/ttyS2 at 115200 baud
2018-12-15 14:07:33,035 - INFO     - PAI.paradox.interfaces.gsm_interface - Started GSM Interface
2018-12-15 14:07:33,105 - ERROR    - PAI.paradox.interfaces.gsm_interface - modem failed
Traceback (most recent call last):
  File "/home/gytis/.local/lib/python3.5/site-packages/serial/serialposix.py", line 501, in read
    'device reports readiness to read but returned no data '
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gytis/pai/paradox/interfaces/gsm_interface.py", line 111, in run
    data = self.port.read(200)
  File "/home/gytis/.local/lib/python3.5/site-packages/serial/serialposix.py", line 509, in read
    raise SerialException('read failed: {}'.format(e))
serial.serialutil.SerialException: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
2018-12-15 14:07:34,110 - INFO     - PAI.paradox.interfaces.gsm_interface - Using /dev/ttyS2 at 115200 baud
2018-12-15 14:07:34,112 - INFO     - PAI.paradox.interfaces.gsm_interface - Started GSM Interface
2018-12-15 14:07:35,067 - INFO     - PAI.paradox.interfaces.gsm_interface - data from serial b'\xc0,\x1f1\\\xb4Dc\xa9\xbc\xb9\xf5\xf8\x11\x00\n\x01\x80hT\xd5*QOL\x96"*111#"}-\x9dUy\x82\xe6\xc4:Y\xf1\xdf\xd1\xff\x1en\xfd/\xb9\xfd\xac\xe8\xd4\xb55\xfb\xdd\x1a\xce\x1a\xb6\xe8\x82\xf6\x84\xe0\x82w8\xd7\x05\xda\x1eqx\xb1\xfd7\xab\xff\\\x8e\xfc4\xe9\xec\x1d\xf0e\xfeQ\x8d\x95\xe7\x9d\xe4\xf99\xcf\xbf\xc1U\xd0\xff\x18kpgz\'.\xf3\x8d\xdf<\x03\xba\xda\xc5>\x9f\xd3\xf7\xfd:l\xca\x11$\xc5\xf9\xac\xf8\xa3\xbdR\xd4\xf0\xde[\xcd\xdd\xa9\x8e\xfcP\xc1a\x97=\xcc\xc1\xd0\xd7#-\xf0g\xea\x9bEyD0)\xe3\xf7\tj\xae\xad\x9f\xe2\xad\x1d\xc8\xb5\xb4\xa5\xfe=^:\xb2\xf2\xf6\xb1\xc3P\xca\x85\xbb\xd5\xf3(\n:'
```

I've uncommented https://github.com/jpbarraca/pai/blob/master/paradox/interfaces/gsm_interface.py#L132 to see the actual exception (`modem failed`)

**Comment by gytisgreitai** [comment]
seems to be reproducible with simple python serial read program, so probably hardware issue.
