### ISSUE TITLE
SP6000 panel, IP Causes Loss of date and time

### ISSUE THREAD

**Issue by psyciknz** [jpbarraca/pai#44]
**System**
Describe your panel model, access mode (Serial, IP150, etc..) and hardware.
SP6000 panel IP150 v 1.39

**Describe the bug**
Took a bit of getting the config right...I'm unsure the difference between IP_CONNECTION and IP_INTERFACE

With a 1.39 FW module which should I use.

Anyway, with my module password (text) in the IP_CONNECTION_PASSWORD and a PASSWORD of the PC Panel Password (it's a 4 digit pin) - that value "PASSWORD" isn't listed in the default.py I notice.  I managed to get a connection and start seeing motion events.

But after doing that I receive an email from the panel about a loss 
```
From your Paradox internet module
Site: SiteID
Message: Loss of time and date restored
Time: 14 Feb 2019 18:48
```

And the time seems to have reset itself to GMT given it's 15 Feb 2019 07:48 at time of writing.

I also think I'm getting an mqtt error....but I'll get the connection issue first.

**To Reproduce**
1. Start script '...'

**Logs**
PLEASE DO NOT SEND LOGS IN CLEAR TEXT AS THEY MAY CONTAIN SENSITIVE INFORMATION
If you wish to add a log (which will greatly help us), please follow the following instructions:

1. Go to https://keybase.io/encrypt
2. Write 'jpbarraca' as the recipient
3. Write your log or add a link to the log file (if using services such as dropbox).
4. Click Encrypt
5. Save the result to a text file and add it as an attachment.

**Comment by psyciknz** [comment]
Here's the info log:
```
2019-02-14 19:10:41,549 - INFO     - PAI - Starting Paradox Alarm Interface
2019-02-14 19:10:41,550 - INFO     - PAI - Console Log level set to 20
2019-02-14 19:10:41,550 - INFO     - PAI.paradox.interfaces.interface_manager - Using MQTT Interface
2019-02-14 19:10:41,689 - INFO     - PAI.paradox.interfaces.interface_manager - Using IP Interface
2019-02-14 19:10:41,724 - INFO     - PAI.paradox.interfaces.ip_interface - Starting IP Interface
2019-02-14 19:10:41,726 - INFO     - PAI.paradox.interfaces.ip_interface - IP Open
2019-02-14 19:10:41,728 - INFO     - PAI.paradox.interfaces.mqtt_interface - MQTT Broker Connected
2019-02-14 19:10:42,726 - INFO     - PAI - Using IP Connection
2019-02-14 19:10:42,870 - INFO     - PAI - Starting...
2019-02-14 19:10:42,871 - INFO     - PAI.paradox.paradox - Connecting to interface
2019-02-14 19:10:42,879 - INFO     - PAI.paradox.connections.ip_connection - Authentication Success. Panel version 20, firmware: 1.50
2019-02-14 19:10:42,901 - INFO     - PAI.paradox.connections.ip_connection - Session Established with IP Module
INFO:PAI.paradox.connections.ip_connection:Session Established with IP Module
2019-02-14 19:10:42,901 - INFO     - PAI.paradox.paradox - Connecting to panel
INFO:PAI.paradox.paradox:Connecting to panel
2019-02-14 19:10:42,902 - INFO     - PAI.paradox.paradox - Initiating communication
INFO:PAI.paradox.paradox:Initiating communication
2019-02-14 19:10:43,428 - INFO     - PAI.paradox.paradox - Found Panel SP6000 version 6.16 build 2
INFO:PAI.paradox.paradox:Found Panel SP6000 version 6.16 build 2
2019-02-14 19:10:43,429 - INFO     - PAI.paradox.paradox - Starting communication
INFO:PAI.paradox.paradox:Starting communication
2019-02-14 19:10:43,585 - INFO     - PAI.paradox.hardware.spectra_magellan.panel - Initializing communication
INFO:PAI.paradox.hardware.spectra_magellan.panel:Initializing communication
2019-02-14 19:10:43,706 - INFO     - PAI.paradox.hardware.spectra_magellan.panel - Authentication Success
INFO:PAI.paradox.hardware.spectra_magellan.panel:Authentication Success
2019-02-14 19:10:43,840 - WARNING  - PAI.paradox.paradox - Missing type system for event: 48.2 Software log on
WARNING:PAI.paradox.paradox:Missing type system for event: 48.2 Software log on
2019-02-14 19:10:44,131 - WARNING  - PAI.paradox.paradox - Missing type system for event: 45.6 Clock loss restore
WARNING:PAI.paradox.paradox:Missing type system for event: 45.6 Clock loss restore
2019-02-14 19:10:44,131 - INFO     - PAI.paradox.hardware.spectra_magellan.panel - Updating Labels from Panel
INFO:PAI.paradox.hardware.spectra_magellan.panel:Updating Labels from Panel
2019-02-14 19:10:44,132 - INFO     - PAI.paradox.hardware.panel - Updating Labels from Panel
INFO:PAI.paradox.hardware.panel:Updating Labels from Panel
2019-02-14 19:10:47,190 - INFO     - PAI.paradox.hardware.panel - Zone: Front door reed, Family room PIR, Lounge PIR, Bed room PIR, Study PIR, Garage, Play Room, Zone 08, Study Reed, Dining Room, Mid toilet Reed, Main door PIR, Smoke 1st floor, Zone 14, Zone 15, Zone 16, Smoke 2nd floor, Zone 18, Zone 19, Zone 20, Zone 21, Zone 22, Zone 23, Zone 24, Zone 25, Zone 26, Zone 27, Zone 28, Zone 29, Zone 30, Zone 31, Zone 32
INFO:PAI.paradox.hardware.panel:Zone: Front door reed, Family room PIR, Lounge PIR, Bed room PIR, Study PIR, Garage, Play Room, Zone 08, Study Reed, Dining Room, Mid toilet Reed, Main door PIR, Smoke 1st floor, Zone 14, Zone 15, Zone 16, Smoke 2nd floor, Zone 18, Zone 19, Zone 20, Zone 21, Zone 22, Zone 23, Zone 24, Zone 25, Zone 26, Zone 27, Zone 28, Zone 29, Zone 30, Zone 31, Zone 32
2019-02-14 19:10:48,739 - INFO     - PAI.paradox.hardware.panel - Pgm: Garage Door, Output 02, Output 03, Output 04, Output 05, Output 06, Output 07, Output 08, Output 09, Output 10, Output 11, Output 12, Output 13, Output 14, Output 15, Output 16
INFO:PAI.paradox.hardware.panel:Pgm: Garage Door, Output 02, Output 03, Output 04, Output 05, Output 06, Output 07, Output 08, Output 09, Output 10, Output 11, Output 12, Output 13, Output 14, Output 15, Output 16
2019-02-14 19:10:48,934 - INFO     - PAI.paradox.hardware.panel - Partition: Area 1, Area 2
INFO:PAI.paradox.hardware.panel:Partition: Area 1, Area 2
2019-02-14 19:10:50,289 - WARNING  - PAI.paradox.paradox - Missing property open in zone/Main door PIR
WARNING:PAI.paradox.paradox:Missing property open in zone/Main door PIR
2019-02-14 19:10:54,729 - INFO     - PAI.paradox.hardware.panel - User: System Master, Master 1, Master 2, monitoring, st just remote, User 06, User 07, User 08, User 09, User 10, User 11, User 12, User 13, User 14, User 15, User 16, User 17, User 18, User 19, User 20, User 21, User 22, User 23, User 24, User 25, User 26, User 27, User 28, User 29, User 30, User 31, User 32
INFO:PAI.paradox.hardware.panel:User: System Master, Master 1, Master 2, monitoring, st just remote, User 06, User 07, User 08, User 09, User 10, User 11, User 12, User 13, User 14, User 15, User 16, User 17, User 18, User 19, User 20, User 21, User 22, User 23, User 24, User 25, User 26, User 27, User 28, User 29, User 30, User 31, User 32
2019-02-14 19:10:56,246 - INFO     - PAI.paradox.hardware.panel - Bus-Module: Bus Module 01, Bus Module 02, Bus Module 03, Bus Module 04, Bus Module 05, Bus Module 06, Bus Module 07, Bus Module 08, Bus Module 09, Bus Module 10, Bus Module 11, Bus Module 12, Bus Module 13, Bus Module 14, Bus Module 15
INFO:PAI.paradox.hardware.panel:Bus-Module: Bus Module 01, Bus Module 02, Bus Module 03, Bus Module 04, Bus Module 05, Bus Module 06, Bus Module 07, Bus Module 08, Bus Module 09, Bus Module 10, Bus Module 11, Bus Module 12, Bus Module 13, Bus Module 14, Bus Module 15
2019-02-14 19:10:56,439 - INFO     - PAI.paradox.hardware.panel - Repeater: Repeater 1, Repeater 2
INFO:PAI.paradox.hardware.panel:Repeater: Repeater 1, Repeater 2
2019-02-14 19:10:59,755 - INFO     - PAI.paradox.hardware.panel - Keypad: Wireless Keyp 1, Wireless Keyp 2, Wireless Keyp 3, Wireless Keyp 4, Wireless Keyp 5, Wireless Keyp 6, Wireless Keyp 7, Wireless Keyp 8
INFO:PAI.paradox.hardware.panel:Keypad: Wireless Keyp 1, Wireless Keyp 2, Wireless Keyp 3, Wireless Keyp 4, Wireless Keyp 5, Wireless Keyp 6, Wireless Keyp 7, Wireless Keyp 8
2019-02-14 19:10:59,850 - INFO     - PAI.paradox.hardware.panel - Site: Your Alarm Site
INFO:PAI.paradox.hardware.panel:Site: Your Alarm Site
2019-02-14 19:11:00,165 - INFO     - PAI.paradox.hardware.panel - Siren: Wireless Siren 1, Wireless Siren 2, Wireless Siren 3
INFO:PAI.paradox.hardware.panel:Siren: Wireless Siren 1, Wireless Siren 2, Wireless Siren 3
2019-02-14 19:11:00,166 - INFO     - PAI.paradox.paradox - Connection OK
INFO:PAI.paradox.paradox:Connection OK
2019-02-14 19:11:01,747 - INFO     - PAI.paradox.interfaces.ip_interface - Ready
INFO:PAI.paradox.interfaces.ip_interface:Ready
```

**Comment by jpbarraca** [comment]
For us a CONNECTION is a way of connecting to the Panel. An Interface is a way that PAI provides for other applications to interact. The IP_CONNECTION connects to an IP150, and IP_INTERFACE provides a simple "emulation" of an IP150, allowing babyware to configure the panel.

That message is sent upon a new connection because we sync the time of the panel with the host. It seems like we need to account for the timezone.

**Comment by psyciknz** [comment]
So I can ignore the IP-_INTERFACE as this point and just leave the IP_CONNECTION details?

And did I get the PW/Module Password right, that one is the text password entered into the web site, the other is the PC Panel Password (as used by babyware).

Ah right, on so new connection you set the time of the panel.. Since I was using docker, I assume I can fix this myself by using the TZ = Pacific/Auckland timezone on the container?

**Comment by psyciknz** [comment]
So I still seem to get the error, but at least the panel is being given the right time now.  Is there a check between the code and the panel for the current time?

**Comment by psyciknz** [comment]
With the following:
POWER_UPDATE_INTERVAL = 60      	# Interval between updates of the battery, DC and VDC voltages
Should I see power updates being posted.
These normally come out with the Hex 50 event, and hex 51 being partitions, hex 52 zones I think. up to 55, then it cycles back.

**Comment by jpbarraca** [comment]
It should, but the current dev is not doing it. I will see what is going on.

**Comment by jpbarraca** [comment]
Can you please test?

**Comment by psyciknz** [comment]
Trying to test now.
If running in docker, you need to edit the DockerFile for the git command: 'RUN git clone --single-branch --branch dev https://github.com/jpbarraca/pai.git /opt/pai'
So it picks up the Dev branch....

**Comment by psyciknz** [comment]
I'm getting a 
```
Step 14/16 : VOLUME ["/etc/pai/pai.conf"]
cannot mount volume over existing file, file exists /hdd/zdocker/overlay2/2f10adfb3c63572f49cf5540a2544202c71186ac5a675a8ece38fcd8eef351be/merged/etc/pai/pai.conf
```
when building the docker image

**Comment by psyciknz** [comment]
So to get around this I remove the 
``'
RUN cp /opt/pai/config/pai.conf.example /etc/pai/pai.conf
```
line.  THen when running I get a further error:
```
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from paradox import main
  File "/src/pai/paradox/main.py", line 17, in <module>
    from paradox.config import config as cfg
  File "/src/pai/paradox/config.py", line 170, in <module>
    config = Config()
  File "/src/pai/paradox/config.py", line 133, in __init__
    self.load()
  File "/src/pai/paradox/config.py", line 156, in load
    exec(f.read(), None, entries)
  File "<string>", line 5, in <module>
ModuleNotFoundError: No module named 'config.defaults'
```

Looks like quite a bit around the config has changed.....what i might do to test just that update, is to update the paradox.py and change the 
```
now = datetime.datetime.now()
```
to 
```
now = time.localtime()
```
as you did.

**Comment by psyciknz** [comment]
Also might be worth noting int he readme for docker:
 docker run -it --name paradoxpai --rm -v **/etc/timezone:/etc/timezone** -v **/etc/localtime:/etc/localtime** -v /src/pai/config/user.py:/opt/paradox/config/user.py pai

Is pretty important, else the docker container is GMT.

**Comment by psyciknz** [comment]
But once the date and time is correct (and correct time zone), a restart still seems to cause the loss of date time alert, even though there should be no difference.

**Comment by psyciknz** [comment]
Regardless the service is working pretty well.  I'm still not getting panel voltages/time etc on the x50/x51 status....which are useful if nothing else for verifying the connection to the panel is up.

**Comment by psyciknz** [comment]
This looks like where you request the status, but I never see it causing anythign to happen:
```
try:
                for i in cfg.STATUS_REQUESTS:
                    reply = self.panel.request_status(i)
                    if reply is not None:
                        tstart = time.time()
                        self.panel.handle_status(reply)
```
I should download all the code so I can run it in debug.  There's probably part I can contribute to (mostly Spectra specific).

**Comment by psyciknz** [comment]
So I've look and I can see it updating the power stats, but they seem to exit out of here:
```
if type_key not in elements:
            return
```
in paradox.py Update_properties.  It seems to get the system elements list, but does this mean when setting it up there was never a key added for 'power' so it doesnt receive a new value?

**Comment by jpbarraca** [comment]
The docker container is built from the main branch as we consider that the Dev branch is unstable.

Thanks for the debug. I had noticed this. It has to do with changes made to the parsing of the status and events. 
Data about power and some troubles are not being published.

**Comment by psyciknz** [comment]
Now that I can run it in Vistula studio code, I’d agree.  Took me a bit to get my head around how you’re doing things.

**Comment by jpbarraca** [comment]
EVO and MG/SP are very different from each other. In order to keep some logic generic, we had to do things in a not so obvious way.

**Comment by jpbarraca** [comment]
Duplicate with #50. Closing to focus discussion.
