### ISSUE TITLE
WinError 10056 error on recv(1024)

### ISSUE THREAD

**Issue by Fisherijus** [jpbarraca/pai#46]
this is my log:

2019-02-20 22:08:28,478 - INFO     - PAI - Starting Paradox Alarm Interface
2019-02-20 22:08:28,479 - INFO     - PAI - Console Log level set to 10
2019-02-20 22:08:29,480 - INFO     - PAI - Using IP Connection
2019-02-20 22:08:29,646 - INFO     - PAI - Starting...
2019-02-20 22:08:29,647 - INFO     - PAI.paradox.paradox - Connecting to interface
2019-02-20 22:08:29,654 - DEBUG    - PAI.paradox.connections.ip_connection - Authenticating with IP Module
2019-02-20 22:08:29,655 - DEBUG    - PAI.paradox.connections.ip_connection - PC -> IP b'aa04000309f0000001eeeeeeeeeeeeee'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2019-02-20 22:08:34,909 - ERROR    - PAI.paradox.connections.ip_connection - Unable to establish session with IP Module
Traceback (most recent call last):
  File "C:\paradox150\pai-master\pai-master\paradox\connections\ip_connection.py", line 138, in connect_to_panel
    data = self.socket.recv(1024)
socket.timeout: timed out
2019-02-20 22:08:34,913 - ERROR    - PAI.paradox.connections.ip_connection - Try 2/3. Unable to connect to IP Module
Traceback (most recent call last):
  File "C:\paradox150\pai-master\pai-master\paradox\connections\ip_connection.py", line 60, in connect
    self.socket.connect((self.host, self.port))
OSError: [WinError 10056] A connect request was made on an already connected socket
2019-02-20 22:08:34,918 - ERROR    - PAI.paradox.connections.ip_connection - Try 3/3. Unable to connect to IP Module
Traceback (most recent call last):
  File "C:\paradox150\pai-master\pai-master\paradox\connections\ip_connection.py", line 60, in connect
    self.socket.connect((self.host, self.port))
OSError: [WinError 10056] A connect request was made on an already connected socket

it seems that after it sends the first packet after connecting to the module and tries to read stream from the socket, it receives the exception, cause there is nothing to read..i tries to put some delay in between send and recv but did not help.

**Comment by yozik04** [comment]
Are you sure nothing is connected to the panel at the same time when you run pai?
Babyware, Winload?

**Comment by jpbarraca** [comment]
If the panel fw is higher than 4, it is better to use the SITE ID, and not the direct IP.

**Comment by yozik04** [comment]
@Fisherijus Which method you used install python on Windows?

**Comment by yozik04** [comment]
Closing due to inactivity.
