### ISSUE TITLE
EVO192 256K v7.01.004 serial connection problem

### ISSUE THREAD

**Issue by yellowonblack** [jpbarraca/pai#62]
Few days ago I found this amazing project and I would like to thank contributors for all the work and offer my support on testing new functionalities.

Right now I'm using an EVO192 panel with firmware EVO192_256K_V7_01_004 and IP150 v4.30.

I started using the IP connection which works quite stable with my IP150 v.4.30  but there is a quite big delay between the moment one zone triggers and the MQTT message is published and sometimes the event is not even published on MQTT topic (because of the 10 seconds delay between two readings).
So, last night I start experimenting with the serial connection, using 3 different serial-to-USB devices connected to a Raspberry PI3 with the last Raspbian up-to-date version:
1. Paradox 307USB - FT232R USB UART
2. PL2303
3. CP2102 USB to UART Bridge Controller

With first 2 devices I didn't had any success as no data was received on the /dev/ttyUSB0.
The only partial success I had is only using CP2102, connecting only Rx and Tx wires on the EVO serial port, but when starting PAI I have the following error:

2019-03-30 13:32:37,228 - INFO     - PAI.paradox.paradox - Connecting to interface
2019-03-30 13:32:37,229 - DEBUG    - PAI.paradox.connections.serial_connection - Opening Serial port: /dev/ttyUSB0
2019-03-30 13:32:37,243 - DEBUG    - PAI.paradox.connections.serial_connection - Serial port open!
2019-03-30 13:32:37,245 - INFO     - PAI.paradox.paradox - Connecting to panel
2019-03-30 13:32:37,245 - INFO     - PAI.paradox.paradox - Initiating communication
2019-03-30 13:32:37,291 - DEBUG    - PAI.paradox.paradox - Unknown message: 72  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  72 
2019-03-30 13:32:37,334 - DEBUG    - PAI.paradox.paradox - Unknown message: 72  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  72 
2019-03-30 13:32:37,376 - DEBUG    - PAI.paradox.paradox - Unknown message: 72  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  72 
2019-03-30 13:32:37,418 - DEBUG    - PAI.paradox.paradox - Unknown message: 72  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  72 
2019-03-30 13:32:37,461 - DEBUG    - PAI.paradox.paradox - Unknown message: 72  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  72 
2019-03-30 13:32:37,503 - DEBUG    - PAI.paradox.paradox - Unknown message: 72  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  72 
2019-03-30 13:32:37,504 - WARNING  - PAI.paradox.paradox - Unknown panel. Some features may not be supported
2019-03-30 13:32:37,505 - INFO     - PAI.paradox.paradox - Starting communication
2019-03-30 13:32:37,550 - DEBUG    - PAI.paradox.paradox - Unknown message: 5f  20  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  02  00  00  81 
2019-03-30 13:32:37,593 - DEBUG    - PAI.paradox.paradox - Unknown message: 5f  20  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  02  00  00  81 
2019-03-30 13:32:37,635 - DEBUG    - PAI.paradox.paradox - Unknown message: 5f  20  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  02  00  00  81 
2019-03-30 13:32:37,678 - DEBUG    - PAI.paradox.paradox - Unknown message: 5f  20  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  02  00  00  81 
2019-03-30 13:32:37,720 - DEBUG    - PAI.paradox.paradox - Unknown message: 5f  20  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  02  00  00  81 
2019-03-30 13:32:37,762 - DEBUG    - PAI.paradox.paradox - Unknown message: 5f  20  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  02  00  00  81

Do you have any recommendation for this problem? Thanks again.

**Comment by yozik04** [comment]
I guess you connect raspberry Pi and IP150 to the serial port at the same time?

**Comment by yellowonblack** [comment]
No, IP150 is removed and I connect only the RPi. I just tried again with PL2303 (only Rx and Tx) and I get the same error like above.

**Comment by yozik04** [comment]
Did you tried master or dev branch? I have EVO192 but not 256K version. I have downgraded my IP150 to <4 firmware. Works fine. Never tried serial connection.

This 72 00 ... 00 72 message is actually sent by PAI. It is strange that you receive it back.

**Comment by yozik04** [comment]
When you connect serial port, you need to connect RX, TX and GND. Ground must be connected.

**Comment by yozik04** [comment]
Looking into SerialCommunication class code right now. I see that there is 9600 baud rate. Which is not true for EVO.

EVO supports 57600 and 38400(default) baud rates only.

Let me make a configuration parameter for that...

**Comment by yellowonblack** [comment]
I hope I'm using the correct pin layout, so on EVO board the serial pins are from up-to-down: Rx, Tx, GND, AUX+.
If I connect GND this is what I get:

2019-03-30 14:29:54,059 - INFO     - PAI - Starting Paradox Alarm Interface
2019-03-30 14:29:54,060 - INFO     - PAI - Console Log level set to 10
2019-03-30 14:29:54,060 - INFO     - PAI.paradox.interfaces.interface_manager - Using MQTT Interface
2019-03-30 14:29:54,196 - DEBUG    - PAI.paradox.interfaces.interface_manager - Registering Interface mqtt
2019-03-30 14:29:54,212 - INFO     - PAI.paradox.interfaces.mqtt_interface - MQTT Broker Connected
2019-03-30 14:29:54,212 - DEBUG    - PAI.paradox.interfaces.mqtt_interface - Subscribing to topics in paradox/control
2019-03-30 14:29:55,199 - INFO     - PAI - Using Serial Connection
2019-03-30 14:29:55,226 - INFO     - PAI - Starting...
2019-03-30 14:29:55,227 - INFO     - PAI.paradox.paradox - Disconnecting from the Alarm Panel
2019-03-30 14:29:55,228 - INFO     - PAI.paradox.paradox - Disconnected
2019-03-30 14:29:55,228 - INFO     - PAI.paradox.paradox - Connecting to interface
2019-03-30 14:29:55,229 - DEBUG    - PAI.paradox.connections.serial_connection - Opening Serial port: /dev/ttyUSB0
2019-03-30 14:29:55,233 - DEBUG    - PAI.paradox.connections.serial_connection - Serial port open!
2019-03-30 14:29:55,235 - INFO     - PAI.paradox.paradox - Connecting to panel
2019-03-30 14:29:55,235 - INFO     - PAI.paradox.paradox - Initiating communication
2019-03-30 14:30:25,281 - WARNING  - PAI.paradox.paradox - Unknown panel. Some features may not be supported
2019-03-30 14:30:25,282 - INFO     - PAI.paradox.paradox - Starting communication
2019-03-30 14:30:55,326 - ERROR    - PAI - Unable to connect to alarm
2019-03-30 14:30:58,331 - INFO     - PAI - Starting...
2019-03-30 14:30:58,331 - INFO     - PAI.paradox.paradox - Disconnecting from the Alarm Panel
2019-03-30 14:30:58,333 - ERROR    - PAI - Restarting
Traceback (most recent call last):
  File "/home/pi/pai/paradox/main.py", line 103, in main
    alarm.disconnect()
  File "/home/pi/pai/paradox/paradox.py", line 540, in disconnect
    self.connection.write(self.panel.get_message('CloseConnection').build(dict()))
  File "/home/pi/pai/paradox/hardware/panel.py", line 58, in get_message
    raise ResourceWarning('{} parser not found'.format(name))
ResourceWarning: CloseConnection parser not found

**Comment by yozik04** [comment]
Please checkout **dev** branch and add setting to config

`SERIAL_BAUD = 38400`

**Comment by yellowonblack** [comment]
No luck. Tried both 38400 and 57600.
Could you confirm that PINs layout the Serial port on EVO192 is correct:  Rx, Tx, GND, AUX+ (from the top down)?

**Comment by yozik04** [comment]
![pinout](https://user-images.githubusercontent.com/2420038/55278400-7e9a3f00-5314-11e9-8cc2-26baae056405.jpg)

**Comment by yozik04** [comment]
Try to change Rx and Tx.

In Babyware you can set setting to broadcast events on the serial port then you should see some output when you trigger zones. Use screen or other terminal supporting serial connection. 

`$ screen /dev/ttyUSB0 38400`

**Comment by yellowonblack** [comment]
Thanks @yozik04 for your help.

During my tests today I found the following:

1. Serial baud for EVO192 has to be 57600. Any other baud does not work for me.
2. Using Paradox 307USB - FT232R USB UART and setting the correct baud make the initial connection with the panel works but it doesn't read any zone/area labels. See below output.
3. Using CP2102 USB to UART Bridge Controller (and Tx from CP2102 to Tx on EVO, and Rx from CP2102 to Rx on EVO + GND ) it has the same behaviour. My wrong presumtion was that I should use Tx to Rx and Rx to Tx but this doesn't work.

Using like this I get no events on MQTT except the initial messages. No messages when zone status changes, nothing.
Mar 30 19:22:04 paradox/interface/MQTTInterface online
Mar 30 19:22:05 paradox/events {"message": "Special events: WinLoad in (connected)", "additional_data": {}, "minor": 4, "label": "", "major": 45, "partition": 0, "module": "\u0000\u0000\u0000\u0000", "label_type": "\u0000", "timestamp": "2019-03-30T19:21:00", "type": "system", "name": "-", "level": "INFO", "tags": [], "id": null, "change": {}}

I then followed your advice and enabled Transmit Zone Status on Serial Port in EVO using Babyware. After this I get zone change status messages but as events:
Mar 30 19:23:18 paradox/events {"message": "Zone 1 Office open", "additional_data": {}, "minor": 11, "label": "1 Office", "major": 1, "partition": 1, "module": "\u0000\u0000\u0000\u0000", "label_type": "\u0002", "timestamp": "2019-03-30T19:22:00", "type": "zone", "name": "-", "level": "DEBUG", "tags": [], "id": 11, "change": {"open": true}}
Mar 30 19:23:26 paradox/events {"message": "Zone 1 Office OK", "additional_data": {}, "minor": 11, "label": "1 Office", "major": 0, "partition": 1, "module": "\u0000\u0000\u0000\u0000", "label_type": "\u0002", "timestamp": "2019-03-30T19:22:00", "type": "zone", "name": "-", "level": "DEBUG", "tags": [], "id": 11, "change": {"open": false}}

The main advantage of this is that is instant, no delays, imediate the senor detect movement you get a MQTT message.

The output when starting PAI:

2019-03-30 18:10:32,195 - ERROR    - PAI.paradox.hardware.evo.panel - Initialization Failed
2019-03-30 18:10:32,196 - ERROR    - PAI - Unable to connect to alarm
2019-03-30 18:10:33,198 - INFO     - PAI - Starting...
2019-03-30 18:10:33,198 - INFO     - PAI.paradox.paradox - Disconnecting from the Alarm Panel
2019-03-30 18:10:33,261 - INFO     - PAI.paradox.paradox - Disconnected
2019-03-30 18:10:33,262 - INFO     - PAI.paradox.paradox - Connecting to interface
2019-03-30 18:10:33,263 - DEBUG    - PAI.paradox.connections.serial_connection - Opening Serial port: /dev/ttyUSB0
2019-03-30 18:10:33,277 - DEBUG    - PAI.paradox.connections.serial_connection - Serial port open!
2019-03-30 18:10:33,278 - DEBUG    - PAI.paradox.connections.serial_connection - Serial port baud: 57600
2019-03-30 18:10:33,279 - INFO     - PAI.paradox.paradox - Connecting to panel
2019-03-30 18:10:33,280 - INFO     - PAI.paradox.paradox - Initiating communication
2019-03-30 18:10:33,308 - INFO     - PAI.paradox.paradox - Found Panel EVO192 version 7.1 build 4
2019-03-30 18:10:33,309 - INFO     - PAI.paradox.paradox - Starting communication
2019-03-30 18:10:33,347 - INFO     - PAI.paradox.hardware.evo.panel - Initializing communication
2019-03-30 18:10:33,393 - DEBUG    - PAI.paradox.paradox - Handle Event: <class 'paradox.event.Event'>
module = b'\x00\x00\x00\x00'
raw = Container: 
    po = Container: 
        command = 14
        status = Container: 
            reserved = False
            alarm_reporting_pending = False
            Winload_connected = True
            NeWare_connected = False
    event_source = 255
    event_nr = 3432
    time = 2019-03-30 19:09:00
    event = Container: 
        major = 45
        partition = 0
        minor = 4
        minor2 = 0
    partition = 0
    module_serial = b'\x00\x00\x00\x00' (total 4)
    label_type = b'\x00' (total 1)
    label = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' (total 16)
change = {}
minor = 4
timestamp = 2019-03-30 19:09:00
type = system
label_type = b'\x00'
level = EventLevel.INFO
additional_data = {}
label_provider = <bound method Paradox.get_label of <paradox.paradox.Paradox object at 0x76305e50>>
message = Special events: WinLoad in (connected)
label = 
id = None
tags = []
major = 45
partition = 0
2019-03-30 18:10:33,394 - WARNING  - PAI.paradox.paradox - Missing element ID in system/

**Comment by yellowonblack** [comment]
Monitoring for some more time:

- Every few minutes there are errors like:
2019-03-30 19:57:27,935 - ERROR    - PAI.paradox.hardware.evo.panel - Initialization Failed
2019-03-30 19:57:27,935 - ERROR    - PAI - Unable to connect to alarm

- Every-time a zone status change occurs there are DEBUG logs (but these appear because of the enabled option in the EVO Panel - Transmit Zone Status on Serial Port ):

2019-03-30 19:57:22,921 - DEBUG    - PAI.paradox.paradox - Handle Event: <class 'paradox.event.Event'>
tags = []
minor = 11
id = 11
label = 1 Office
type = zone
label_provider = <bound method Paradox.get_label of <paradox.paradox.Paradox object at 0x7627fdb0>>
raw = Container: 
    po = Container: 
        command = 14
        status = Container: 
            reserved = False
            alarm_reporting_pending = False
            Winload_connected = True
            NeWare_connected = False
    event_source = 255
    event_nr = 3985
    time = 2019-03-30 20:56:00
    event = Container: 
        minor2 = 0
        partition = 1
        major = 0
        minor = 11
    partition = 1
    module_serial = b'\x00\x00\x00\x00' (total 4)
    label_type = b'\x02' (total 1)
    label = b'1 Office        ' (total 16)
message = Zone 1 Office OK
partition = 1
additional_data = {}
module = b'\x00\x00\x00\x00'
level = EventLevel.DEBUG
change = {'open': False}
label_type = b'\x02'
timestamp = 2019-03-30 20:56:00
major = 0
2019-03-30 19:57:22,922 - WARNING  - PAI.paradox.paradox - Missing type zone for event: 0.11 Zone 1 Office OK

**Comment by yozik04** [comment]
Please send me full debug log to my nickname @gmail.com

You can enable dumping messages and packets as well.

There is also a setting to dump eeprom and ram from the panel. That would also be useful.

**Comment by yozik04** [comment]
256K is different from my EVO192. There could be labels in a different place.

**Comment by yozik04** [comment]
About initialization failed. To fix it I will need a dump of initial communication between Babyware and the Panel.

**Comment by yellowonblack** [comment]
Could you recommend how I should do the dump of the serial communication between Babyware and EVO. 
Also, I enabled DEVELOPMENT_DUMP_MEMORY = True in pai.conf but I do not find any file ('eeprom.bin' or 'ram.bin'), as I think the execution get stucked in the initialization.

2019-03-31 00:18:26,445 - ERROR    - PAI.paradox.hardware.evo.panel - Initialization Failed
2019-03-31 00:18:26,450 - ERROR    - PAI - Unable to connect to alarm

**Comment by yozik04** [comment]
Indeed. Memory dump happens after initialization.

Maybe http://www.serial-port-monitor.com is good?
Never did myself.

Alternative option is to connect IP150 back and sniff IP traffic from Babyware to IP150.
But I will need your password to decode the traffic. If you can change it for the period of capturing it would be good.

**Comment by yellowonblack** [comment]
I just sent you the capture file with the serial communication on COM port between Babyware 5.2.5 and EVO192 256K v7.01.004. This includes the connect sequence + few seconds waiting + disconnect sequence.
I used 307USB cable and as software https://www.aggsoft.com/serial-port-monitor/serial-port-sniffer.htm

**Comment by yozik04** [comment]
I see that it connected properly in this comment. Didn't it? https://github.com/jpbarraca/pai/issues/62#issuecomment-478277656

Can you please send me full log with

```
LOGGING_DUMP_MESSAGES=True
LOGGING_DUMP_PACKETS=True
```

I am checking your serial dump and it looks the same as for previous EVO. I need to know exact step where it fails.

**Comment by yellowonblack** [comment]
Yes, it connected somehow but it doesn't transmit anything on the MQTT zone/partitions subtopics but only on paradox/events and this because I enable Transmit Status on Serial Output. If this setting is disabled nothing is published on MQTT except the initial paradox/interface/MQTTInterface online.
I will try to generate a full log later and sent it to you.

**Comment by yellowonblack** [comment]
Did an update with the last dev branch and getting this error:

2019-04-01 19:33:44,987 - INFO     - PAI - Starting Paradox Alarm Interface
2019-04-01 19:33:44,988 - INFO     - PAI - Console Log level set to 10
2019-04-01 19:33:44,988 - INFO     - PAI.paradox.interfaces.interface_manager - Using MQTT Interface
2019-04-01 19:33:45,124 - DEBUG    - PAI.paradox.interfaces.interface_manager - Registering Interface mqtt
2019-04-01 19:33:45,147 - INFO     - PAI.paradox.interfaces.mqtt_interface - MQTT Broker Connected
2019-04-01 19:33:45,148 - DEBUG    - PAI.paradox.interfaces.mqtt_interface - Subscribing to topics in paradox/control
2019-04-01 19:33:46,127 - INFO     - PAI - Using Serial Connection
2019-04-01 19:33:46,154 - INFO     - PAI - Starting...
2019-04-01 19:33:46,156 - ERROR    - PAI - Restarting
Traceback (most recent call last):
  File "/home/pi/pai/paradox/main.py", line 103, in main
    if alarm.connect():
  File "/home/pi/pai/paradox/paradox.py", line 99, in connect
    self.clean_session()
  File "/home/pi/pai/paradox/paradox.py", line 558, in clean_session
    if self.connection.connected:
AttributeError: 'SerialCommunication' object has no attribute 'connected'
2019-04-01 19:33:49,165 - INFO     - PAI - Starting...
2019-04-01 19:33:49,166 - ERROR    - PAI - Restarting
Traceback (most recent call last):
  File "/home/pi/pai/paradox/main.py", line 103, in main
    if alarm.connect():
  File "/home/pi/pai/paradox/paradox.py", line 99, in connect
    self.clean_session()
  File "/home/pi/pai/paradox/paradox.py", line 558, in clean_session
    if self.connection.connected:
AttributeError: 'SerialCommunication' object has no attribute 'connected'

**Comment by yozik04** [comment]
Try one more time =)

**Comment by yellowonblack** [comment]
The error is fixed, now I will try to dump the logs and sent it to you.

**Comment by yozik04** [comment]
Try `asyncio` branch. It should work better on initial connection.

**Comment by yozik04** [comment]
@yellowonblack I have created separate branch for your panel for testing. Please checkout  asyncio_evo192_256k and try. This is the only difference in requests between Babyware and PAI.

Another idea: Are you sure the password is right in the config?

**Comment by yellowonblack** [comment]
The password should not be a problem, because for testing I'm just changing in pai.conf the value of CONNECTION_TYPE from IP and Serial, so the same password is accepted on IP connection with siteID.
Do you think could be a problem with the 307USB cable? even so with the same cable I can connect to the panel with Babyware over serial just fine.

I tested b4196b6 and got:

2019-04-07 00:04:10,069 - INFO     - PAI - Starting Paradox Alarm Interface
2019-04-07 00:04:10,070 - INFO     - PAI - Console Log level set to 10
2019-04-07 00:04:10,070 - INFO     - PAI.paradox.interfaces.interface_manager - Using MQTT Interface
2019-04-07 00:04:10,169 - DEBUG    - PAI.paradox.interfaces.interface_manager - Registering Interface mqtt
2019-04-07 00:04:10,188 - INFO     - PAI.paradox.interfaces.mqtt_interface - MQTT Broker Connected
2019-04-07 00:04:10,188 - DEBUG    - PAI.paradox.interfaces.mqtt_interface - Subscribing to topics in paradox/control
2019-04-07 00:04:11,172 - INFO     - PAI - Using Serial Connection
2019-04-07 00:04:11,205 - INFO     - PAI - Starting...
2019-04-07 00:04:11,206 - INFO     - PAI.paradox.paradox - Connecting to interface
2019-04-07 00:04:11,207 - INFO     - PAI.paradox.connections.serial_connection - Connecting to serial port /dev/ttyUSB0
2019-04-07 00:04:11,212 - INFO     - PAI.paradox.connections.serial_connection - Serial port Open
2019-04-07 00:04:11,213 - INFO     - PAI.paradox.connections.serial_connection - Serial port open
2019-04-07 00:04:11,215 - INFO     - PAI.paradox.paradox - Connecting to panel
2019-04-07 00:04:11,215 - INFO     - PAI.paradox.paradox - Initiating communication
2019-04-07 00:04:11,220 - DEBUG    - PAI.paradox.paradox - PC -> A b'72000000000000000000000000000000000000000000000000000000000000000000000072'
2019-04-07 00:04:11,221 - DEBUG    - PAI.paradox.connections.serial_connection - PC -> Serial b'72000000000000000000000000000000000000000000000000000000000000000000000072'
2019-04-07 00:04:21,241 - ERROR    - PAI.paradox.paradox - Failed to connect: Panel did not replied to InitiateCommunication
2019-04-07 00:04:21,242 - ERROR    - PAI - Unable to connect to alarm

I test

**Comment by yozik04** [comment]
Now it failed on first requet. Are you sure serial is connected right? You probably need to resetthe buffer on the serial on both sides.

**Comment by yellowonblack** [comment]
Yep, you are right. I reset the RPi and sent you the new debug logs.

**Comment by yozik04** [comment]
It is weird. But PAI sends exactly identical messages to the panel as Babyware does and does not get successful reply in the end of connection. I am currently out of ideas. Throttling?!

**Comment by yozik04** [comment]
I have found mistake:

```
while len(self.buffer) >= 37:
  # then parse
```

For EVO Successful connection response is 12 06 00 00 00 18

Which is 6 bytes long.

**Comment by yozik04** [comment]
@jpbarraca Is this async serial reading into buffer by chunks? Or every byte separately?

**Comment by yozik04** [comment]
@yellowonblack Please try latest **dev** branch.

**Comment by yellowonblack** [comment]
I tried. Still not connecting properly. I sent you the new logs..

**Comment by yozik04** [comment]
Forgot to change checksum function. Try one more time =)

**Comment by yozik04** [comment]
Nobody used Serial connection with EVO yet. You are the first one.

**Comment by yellowonblack** [comment]
Great @yozik04, now it works. Very happy 👍 ....but... if **LOGGING_DUMP_PACKETS = False** the initialisation process stops at **PAI.paradox.paradox - Initiating communication** (see below). Of course no zone change status is updated on MQTT.

If **LOGGING_DUMP_PACKETS = True** then everything works perfect, or at least the zone change status. I will test also arming, disarming and other later.

2019-04-07 16:58:30,348 - INFO     - PAI - Console Log level set to 10
2019-04-07 16:58:30,348 - INFO     - PAI.paradox.interfaces.interface_manager - Using MQTT Interface
2019-04-07 16:58:30,448 - DEBUG    - PAI.paradox.interfaces.interface_manager - Registering Interface mqtt
2019-04-07 16:58:30,463 - INFO     - PAI.paradox.interfaces.mqtt_interface - MQTT Broker Connected
2019-04-07 16:58:30,464 - DEBUG    - PAI.paradox.interfaces.mqtt_interface - Subscribing to topics in paradox/control
2019-04-07 16:58:31,451 - INFO     - PAI - Using Serial Connection
2019-04-07 16:58:31,485 - INFO     - PAI - Starting...
2019-04-07 16:58:31,487 - INFO     - PAI.paradox.paradox - Connecting to interface
2019-04-07 16:58:31,487 - INFO     - PAI.paradox.connections.serial_connection - Connecting to serial port /dev/ttyUSB0
2019-04-07 16:58:31,493 - INFO     - PAI.paradox.connections.serial_connection - Serial port Open
2019-04-07 16:58:31,494 - INFO     - PAI.paradox.connections.serial_connection - Serial port open
2019-04-07 16:58:31,496 - INFO     - PAI.paradox.paradox - Connecting to panel
2019-04-07 16:58:31,497 - INFO     - PAI.paradox.paradox - Initiating communication

**Comment by yozik04** [comment]
If it stops on first request then probably you need to clear the buffer. Please try. 

Also I have a task for you. 

Please try to set 
SERIAL_THROTTLE to 0. And check if it connects and is stable. If not, try to play with it’s value in range 1 to 100.

**Comment by yellowonblack** [comment]
Even after RPi reboot, having **LOGGING_DUMP_PACKETS = False** hangs at PAI.paradox.paradox - Initiating communication.

SERIAL_WRITE_THROTTLE = 0 
- connects OK
- zone change OK
- overall stability IN_PROGRESS

**Comment by jpbarraca** [comment]
The need to throttle is propably specific to some combinations of panels and hosts. Slower panels with faster hosts.
Not sure why a delay would break the connection process. ...

**Comment by yozik04** [comment]
According to the code we throttle only if there are two subsequent writes. Then second write be delayed.

**Comment by yellowonblack** [comment]
After 2 days running on serial, it looks quite stable, no problems so far.

There are 2 still open issues:
1. Serial connection is initialised only with log debug enabled (at least with my panel model/firmware version) https://github.com/jpbarraca/pai/issues/62#issuecomment-480603933
2. MQTT offline message is missing https://github.com/jpbarraca/pai/issues/57#issuecomment-479912846 (this affects also IP connection with siteID)

**Comment by yozik04** [comment]
@yellowonblack We currently debug nr 1. **dev** branch is currently broken for MG/SP. As it has very slow baudrate the change influences it very much.

**Comment by yozik04** [comment]
@yellowonblack Probably have fixed nr 1. 😅 b030d80

**Comment by yellowonblack** [comment]
I understand and thanks for all your work. I will wait until this will be fixed, as the most important functionality is working now for me.

**Comment by yellowonblack** [comment]
> @yellowonblack Probably have fixed nr 1. 😅 [b030d80](https://github.com/jpbarraca/pai/commit/b030d8028d20ca2071e30a5983a7122f7b5bcdcf)

Quite fast, it took you only few mintutes 😄 
I confirm that now the initialisation is working, also with LOGGING_DUMP_PACKETS = False. I will see if are any problems in the next days.

**Comment by jpbarraca** [comment]
I had this "Could not fully load labels", but it should be fixed with the latest patches. I tried a few times and it always loaded correctly. The throttle is also not required :)
However, they need to be validated in a EVO as there were changes in the serial connection, and there is a special case for one specific EVO message.

**Comment by yozik04** [comment]
@yellowonblack please try serial connection on todays **dev** branch.

**Comment by yozik04** [comment]
SERIAL_WRITE_THROTTLE setting was removed as it is not required.

**Comment by yellowonblack** [comment]
Tests on 2fa1e9f:

1. MQTT offline message now it seems that it's working properly

2. No zone or partition labels are loaded anymore. The only zone changes I get on MQTT are as events

2019-04-10 08:52:01,707 - WARNING  - PAI.paradox.paradox - Missing type zone for event: 0.21 Zone 2_Entrance OK
2019-04-10 08:52:01,878 - ERROR    - PAI.paradox.hardware.panel - Could not fully load labels
2019-04-10 08:52:01,879 - INFO     - PAI.paradox.hardware.panel - User: 
2019-04-10 08:52:01,880 - INFO     - PAI.paradox.hardware.panel - Bus-Module:

**Comment by yozik04** [comment]
Can you please send me log with LOGGING_DUMP_PACKETS. The way @jpbarraca did is the right way. Maybe there is a corner case in EVO.

**Comment by yellowonblack** [comment]
Log sent few minutes ago.

**Comment by yozik04** [comment]
Please verify if serial now works for SP/MG and EVO. c5cb1df

**Comment by jpbarraca** [comment]
MG/SP is ok

**Comment by yellowonblack** [comment]
EVO192 v7.01 - OK. 

Looks good and fast. 🍺 
Now, I could sell my IP150 😄

**Comment by jpbarraca** [comment]
Fantastic ;)
