### ISSUE TITLE
SP4000 Support

### ISSUE THREAD

**Issue by pallasattila** [jpbarraca/pai#70]
SP400 panel with serial connecrtion, possible?
If start run.py

LOG:

2019-04-25 17:01:38,295 - INFO     - PAI - Starting Paradox Alarm Interface
2019-04-25 17:01:38,296 - INFO     - PAI - Console Log level set to 20
2019-04-25 17:01:39,298 - INFO     - PAI - Using Serial Connection
2019-04-25 17:01:39,334 - INFO     - PAI - Starting...
2019-04-25 17:01:39,335 - INFO     - PAI.paradox.paradox - Connecting to interface
2019-04-25 17:01:39,353 - INFO     - PAI.paradox.paradox - Connecting to panel
2019-04-25 17:01:39,354 - INFO     - PAI.paradox.paradox - Initiating communication
2019-04-25 17:01:39,482 - INFO     - PAI.paradox.paradox - Found Panel SP4000 version 5.22 build 0
2019-04-25 17:01:39,483 - INFO     - PAI.paradox.paradox - Starting communication
2019-04-25 17:01:39,594 - ERROR    - PAI.paradox.paradox - Connect error
Traceback (most recent call last):
  File "/root/pai/paradox/paradox.py", line 136, in connect
    self.panel = create_panel(self, reply.fields.value.product_id)
  File "/root/pai/paradox/hardware/__init__.py", line 27, in create_panel
    "We are not sure what panel you have (product_id: %s). Please create an issue. Maybe we can help you." % str(product_id))
NotImplementedError: We are not sure what panel you have (product_id: 26). Please create an issue. Maybe we can help you.
2019-04-25 17:01:39,602 - ERROR    - PAI - Unable to connect to alarm

I tried to modify /root/pai/paradox/hardware/__init__.py file, add the 'SPECTRA_SP4000' to names, but nothing.

Any suggestion?

**Comment by yozik04** [comment]
I have added SPECTRA_SP4000 to enums. "dev" branch

Keep your change and try once again.

**Comment by pallasattila** [comment]
Where is the "dev" branch?

**Comment by jpbarraca** [comment]
Here in github. Clone the repository, enter the pai folder, and do git checkout dev

**Comment by pallasattila** [comment]
I tried, nothing. :(

**Comment by jpbarraca** [comment]
Can you send the log?

**Comment by pallasattila** [comment]
Solved! I added SP4000 and SPECTRA_SP4000. But after connected the panel, this error in log:

2019-04-28 09:52:11,512 - ERROR    - PAI.paradox.paradox - No reply to status request: 4




full log: 

2019-04-28 09:43:44,510 - INFO     - PAI - Starting Paradox Alarm Interface
2019-04-28 09:43:44,511 - INFO     - PAI - Console Log level set to 20
2019-04-28 09:43:44,512 - INFO     - PAI.paradox.interfaces.interface_manager - Using MQTT Interface
2019-04-28 09:43:44,711 - INFO     - PAI.paradox.interfaces.mqtt_interface - MQTT Broker Connected
2019-04-28 09:43:45,680 - INFO     - PAI - Using Serial Connection
2019-04-28 09:43:45,746 - INFO     - PAI - Starting...
2019-04-28 09:43:45,748 - INFO     - PAI.paradox.paradox - Disconnecting from the Alarm Panel
2019-04-28 09:43:45,749 - INFO     - PAI.paradox.paradox - Clean Session
2019-04-28 09:43:45,750 - INFO     - PAI.paradox.paradox - Connecting to interface
2019-04-28 09:43:45,750 - INFO     - PAI.paradox.connections.serial_connection - Connecting to serial port /dev/ttyUSB0
2019-04-28 09:43:45,776 - INFO     - PAI.paradox.connections.serial_connection - Serial port open
2019-04-28 09:43:45,785 - INFO     - PAI.paradox.paradox - Connecting to panel
2019-04-28 09:43:45,786 - INFO     - PAI.paradox.paradox - Initiating communication
2019-04-28 09:43:45,923 - INFO     - PAI.paradox.paradox - Found Panel SP4000 version 5.22 build 0
2019-04-28 09:43:45,924 - INFO     - PAI.paradox.paradox - Starting communication
2019-04-28 09:43:46,094 - INFO     - PAI.paradox.hardware.spectra_magellan.panel - Initializing communication
2019-04-28 09:43:46,254 - INFO     - PAI.paradox.hardware.spectra_magellan.panel - Authentication Success
2019-04-28 09:43:46,417 - WARNING  - PAI.paradox.paradox - Missing element ID in system/?, m/m: 48/2, message: Software log on
2019-04-28 09:43:46,825 - WARNING  - PAI.paradox.paradox - Missing element ID in system/?, m/m: 44/2, message: Battery failure
2019-04-28 09:43:47,009 - WARNING  - PAI.paradox.paradox - Missing type zone for event: 0.1 Zone Zone 01 OK
2019-04-28 09:43:48,010 - WARNING  - PAI.paradox.paradox - Missing type zone for event: 0.1 Zone Zone 01 OK
2019-04-28 09:43:49,288 - WARNING  - PAI.paradox.paradox - Missing type zone for event: 0.1 Zone Zone 01 OK
2019-04-28 09:43:50,323 - WARNING  - PAI.paradox.paradox - Missing element ID in system/Bus Module 01, m/m: 47/0, message: Bus / EBus / Wireless module communication fault restore
2019-04-28 09:43:50,389 - WARNING  - PAI.paradox.paradox - Missing type zone for event: 0.1 Zone Zone 01 OK
2019-04-28 09:43:51,344 - WARNING  - PAI.paradox.paradox - Missing type zone for event: 0.1 Zone Zone 01 OK
2019-04-28 09:44:06,445 - INFO     - PAI.paradox.paradox - Panel time synchronized
2019-04-28 09:44:06,446 - INFO     - PAI.paradox.hardware.panel - Updating Labels from Panel
2019-04-28 09:44:12,492 - ERROR    - PAI.paradox.hardware.panel - Could not fully load labels
2019-04-28 09:44:12,497 - INFO     - PAI.paradox.hardware.panel - User:
2019-04-28 09:44:18,551 - ERROR    - PAI.paradox.hardware.panel - Could not fully load labels
2019-04-28 09:44:18,555 - INFO     - PAI.paradox.hardware.panel - Repeater:
2019-04-28 09:44:24,618 - ERROR    - PAI.paradox.hardware.panel - Could not fully load labels
2019-04-28 09:44:24,622 - INFO     - PAI.paradox.hardware.panel - Site:
2019-04-28 09:44:30,680 - ERROR    - PAI.paradox.hardware.panel - Could not fully load labels
2019-04-28 09:44:30,685 - INFO     - PAI.paradox.hardware.panel - Pgm:
2019-04-28 09:44:36,734 - ERROR    - PAI.paradox.hardware.panel - Could not fully load labels
2019-04-28 09:44:36,738 - INFO     - PAI.paradox.hardware.panel - Partition:
2019-04-28 09:44:42,795 - ERROR    - PAI.paradox.hardware.panel - Could not fully load labels
2019-04-28 09:44:42,800 - INFO     - PAI.paradox.hardware.panel - Keypad:
2019-04-28 09:44:48,844 - ERROR    - PAI.paradox.hardware.panel - Could not fully load labels
2019-04-28 09:44:48,849 - INFO     - PAI.paradox.hardware.panel - Zone:
2019-04-28 09:44:54,909 - ERROR    - PAI.paradox.hardware.panel - Could not fully load labels
2019-04-28 09:44:54,914 - INFO     - PAI.paradox.hardware.panel - Bus-Module:
2019-04-28 09:45:00,970 - ERROR    - PAI.paradox.hardware.panel - Could not fully load labels
2019-04-28 09:45:00,975 - INFO     - PAI.paradox.hardware.panel - Siren:
2019-04-28 09:45:00,980 - INFO     - PAI.paradox.paradox - Connection OK
2019-04-28 09:45:07,038 - ERROR    - PAI.paradox.paradox - No reply to status request: 0
2019-04-28 09:45:13,104 - ERROR    - PAI.paradox.paradox - No reply to status request: 1
2019-04-28 09:45:19,171 - ERROR    - PAI.paradox.paradox - No reply to status request: 2
2019-04-28 09:45:25,233 - ERROR    - PAI.paradox.paradox - No reply to status request: 3

**Comment by jpbarraca** [comment]
What happens if you restart pai after that error?

**Comment by pallasattila** [comment]
Nothing... 

2019-04-28 09:45:00,975 - INFO     - PAI.paradox.hardware.panel - Siren:
2019-04-28 09:45:00,980 - INFO     - PAI.paradox.paradox - Connection OK
2019-04-28 09:45:07,038 - ERROR    - PAI.paradox.paradox - No reply to status request: 0
2019-04-28 09:45:13,104 - ERROR    - PAI.paradox.paradox - No reply to status request: 1
2019-04-28 09:45:19,171 - ERROR    - PAI.paradox.paradox - No reply to status request: 2
2019-04-28 09:45:25,233 - ERROR    - PAI.paradox.paradox - No reply to status request: 3
2019-04-28 09:45:31,305 - ERROR    - PAI.paradox.paradox - No reply to status request: 4
2019-04-28 09:45:37,374 - ERROR    - PAI.paradox.paradox - No reply to status request: 5
2019-04-28 09:45:43,428 - ERROR    - PAI.paradox.paradox - No reply to status request: 0
2019-04-28 09:45:49,495 - ERROR    - PAI.paradox.paradox - No reply to status request: 1
2019-04-28 09:45:55,560 - ERROR    - PAI.paradox.paradox - No reply to status request: 2
2019-04-28 09:46:01,631 - ERROR    - PAI.paradox.paradox - No reply to status request: 3
2019-04-28 09:46:07,695 - ERROR    - PAI.paradox.paradox - No reply to status request: 4
2019-04-28 09:46:13,750 - ERROR    - PAI.paradox.paradox - No reply to status request: 5
2019-04-28 09:46:19,819 - ERROR    - PAI.paradox.paradox - No reply to status request: 0
2019-04-28 09:46:25,886 - ERROR    - PAI.paradox.paradox - No reply to status request: 1

Infinity error. :( 
twice in ten work perfectly, but can't connect to MQTT.. I installed MQTT broker to NanoPi NEO, On android MQTT Dash app. I tired metrics/exchanged/pai and paradox/interface/MQTTInterface.

**Comment by yozik04** [comment]
Enable all debug inconfig and send log from start to me or @jpbarraca email.

**Comment by pallasattila** [comment]
I sent e-mail.

**Comment by jpbarraca** [comment]
Closed as it works. Issue was only related to the serial parser.

**Comment by yozik04** [comment]
@pallasattila you can now remove your change and pull latest "dev".

Latest "dev" should work fine for you.

**Comment by jpbarraca** [comment]
We may need to adjust the number of elements in the panel.

**Comment by jpbarraca** [comment]
@pallasattila can you send me a full log with debug and packet dumps. Just to make sure that it works and is everything is fully detected.
