### ISSUE TITLE
Invalid PC Password

### ISSUE THREAD

**Issue by timsdrew** [jpbarraca/pai#96]
## Alarm system
SP6000 V 4.149
IP150 version 20, Firmware 4.64

## Environment
- Mac OS
- Python version 3.6

## Git branch
Master and Dev

## Describe the bug
 PAI.paradox.paradox - Got ERROR Message: Invalid PC Password
100% Sure password is correct

## To Reproduce
Run script

## Logs
PLEASE DO NOT SEND LOGS IN CLEAR TEXT AS THEY MAY CONTAIN SENSITIVE INFORMATION
If you wish to add a log (which will greatly help us), please follow the following instructions:

1. Go to https://keybase.io/encrypt
2. Write 'jpbarraca' as the recipient
3. Write your log or add a link to the log file (if using services such as dropbox).
4. Click Encrypt
5. Save the result to a text file and add it as an attachment.

Will send logs if required.

**Comment by timsdrew** [comment]
Logs below. Any help will be greatly appreciated
2019-09-03 09:41:35,917 - INFO     - PAI.paradox.connections.ip_connection - Connecting to IP module. Try 1/3
2019-09-03 09:41:35,918 - INFO     - PAI.paradox.connections.ip_connection - Authenticating with IP Module
2019-09-03 09:41:35,926 - INFO     - PAI.paradox.connections.ip_connection - Authentication Success. IP Module version 20, firmware: 4.64, serial: ####
2019-09-03 09:41:35,942 - INFO     - PAI.paradox.connections.ip_connection - Session Established with IP Module
2019-09-03 09:41:35,942 - INFO     - PAI.paradox.paradox - Connecting to panel
2019-09-03 09:41:35,942 - INFO     - PAI.paradox.paradox - Initiating communication
2019-09-03 09:41:36,039 - INFO     - PAI.paradox.paradox - Found Panel SP6000 version 4.149 build 0
2019-09-03 09:41:36,039 - INFO     - PAI.paradox.paradox - Starting communication
2019-09-03 09:41:36,143 - INFO     - PAI.paradox.hardware.spectra_magellan.panel - Initializing communication
2019-09-03 09:41:36,241 - ERROR    - PAI.paradox.paradox - Got ERROR Message: Invalid PC Password
^C2019-09-03 09:41:37,185 - INFO     - PAI.paradox.paradox - Disconnecting from the Alarm Panel
2019-09-03 09:41:37,185 - INFO     - PAI.paradox.paradox - Clean Session
2019-09-03 09:41:37,186 - INFO     - PAI.paradox.paradox - Cleaning previous session. Closing connection
2019-09-03 09:41:37,191 - INFO     - PAI.paradox.paradox - Disconnected from the Alarm Panel

**Comment by timsdrew** [comment]
Fixed myself, sorry.

**Comment by dansity** [comment]
Hi @timsdrew 
Can you please elaborate how did you fix it? I have the very same panel, same IP module and same issue. PC password is 100% correct. My log output is:

```
2023-11-07 13:18:18,070 - INFO     - PAI - Starting Paradox Alarm Interface 3.2.1
2023-11-07 13:18:18,070 - INFO     - PAI - Config loaded from /data/options.json
2023-11-07 13:18:18,070 - INFO     - PAI - Console Log level set to 20
2023-11-07 13:18:18,103 - INFO     - PAI.paradox.interfaces - Starting BasicMQTTInterface Interface
2023-11-07 13:18:18,105 - INFO     - PAI.paradox.interfaces.mqtt.core - MQTT loop started
2023-11-07 13:18:18,109 - INFO     - PAI.paradox.interfaces - Starting HomeAssistantMQTTInterface Interface
2023-11-07 13:18:18,109 - INFO     - PAI - Starting...
2023-11-07 13:18:18,109 - INFO     - PAI.paradox.paradox - Connecting to interface
2023-11-07 13:18:18,109 - INFO     - PAI.paradox.paradox - Using IP Connection
2023-11-07 13:18:18,194 - INFO     - PAI.paradox.connections.ip.connection - Connecting. Try 1/3
2023-11-07 13:18:18,196 - INFO     - PAI.paradox.connections.connection - Connection established
2023-11-07 13:18:18,196 - INFO     - PAI.paradox.connections.ip.commands - Authenticating with IP Module
2023-11-07 13:18:18,200 - INFO     - PAI.paradox.connections.ip.commands - Authentication Success. IP(114) Module version 20, firmware: 5.6, serial: 7201943e
2023-11-07 13:18:18,210 - INFO     - PAI.paradox.connections.ip.commands - Session successfully established with IP Module
2023-11-07 13:18:18,210 - INFO     - PAI.paradox.paradox - Connecting to Panel
2023-11-07 13:18:18,304 - INFO     - PAI.paradox.paradox - Panel Identified SP6000 version 7.14 build 2
2023-11-07 13:18:18,304 - INFO     - PAI.paradox.paradox - Initiating panel connection
2023-11-07 13:18:18,409 - INFO     - PAI.paradox.hardware.spectra_magellan.panel - Installer login
2023-11-07 13:18:18,524 - ERROR    - PAI.paradox.paradox - Got ERROR Message: Invalid PC Password
2023-11-07 13:18:18,526 - ERROR    - PAI.paradox.lib.handlers - Exception caught during message handling
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 112, in handle
    await handler(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 61, in __call__
    result = self._handle(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 649, in handle_error_message
    raise AuthenticationFailed()
paradox.exceptions.AuthenticationFailed
```

**Comment by SimonBruyn** [comment]
Hi, I'm having the same issue. How is this fixed?

**Comment by timsdrew** [comment]
Unfortunately this was over 4 years ago, I cannot recall how I fixed it.
I'm using PAI through homeassistant now, which seems to be significantly
more reliable than running it stand alone.

**Comment by dansity** [comment]
@SimonBruyn  @timsdrew 
I have figured it out. The password is not your pin. set it to 0000. Weirdly connecting to the panel does not need any special authentication just the basic "paradox" password and the 0000 pin
